### ISSUE TITLE
Hello Working just in Reaction.php but in the url /Reaction.html not working still 0 - 0

### ISSUE THREAD

**Issue by essolh** [haydenryan/FBLivePoll#1]
Hello Working just in Reaction.php but in the url /Reaction.html not working still 0 - 0

**Comment by haydenryan** [comment]
Hi,
Please try my free service at https://react.cast.net.au it might be a bit
easier for you

Cheers
Hayden

**Comment by capral85** [comment]
Yes it's not work only 0-0

**Comment by haydenryan** [comment]
Closed for lack of information, please open a new issue if you're still experiencing difficulties Cheers
